url: https://www.subterrabio.com
baseurl: /

# Site settings
title: Subterra
email: info@subterrabio.com
description: "Subterra aims to revolutionize hydrogen exploration and underground hydrogen storage by integrating microbiological insights, geoscience expertise, and advanced computational tools. Unlocking Hydrogen’s Potential, One Microbe at a Time."


# Team names, titles and social links
people:
- name: Andrea Giovannelli
  pic: 1
  position: FOunder &CEO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/giovannelli-andrea/

- name: Martina Cascone
  pic: 2
  position: Founder & CTO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/martina-cascone-643918138/

- name: Valerio Alessi
  pic: 3
  position: Founder & CFO
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/valerio-alessi-aaa56625/

- name: Donato Giovannelli
  pic: 3
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/donatogiovannelli/

- name: David Iacopini
  pic: 3
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/david-iacopini-08199023/

- name: Alberto Vitale Brovarone
  pic: 3
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/alberto-vitale-brovarone-bb46252b2/

- name: Mariano Parente
  pic: 3
  position: Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mariano-parente-5b010723/

- name: Massimo Boccolini
  pic: 3
  position: Founder
  social:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/

# Postal address (add as many lines as necessary)
address:
  - line: University of Naples Federico II
  - line: Naples Italy

# Build settings
markdown: kramdown
permalink: pretty
