url: https://www.subterrabio.com
baseurl: /

# Site settings
title: Subterra
email: info@subterrabio.com
description: "Subterra aims to revolutionize hydrogen exploration and underground hydrogen storage by integrating microbiological insights, geoscience expertise, and advanced computational tools. Unlocking Hydrogen’s Potential, One Microbe at a Time."


# Team names, titles and social links
people:
- name: XXX
  pic: 1
  position: XXX
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: XXX
  pic: 2
  position: XXX
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: XXX
  pic: 3
  position: XXX
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: linkedin
    url:

# Postal address (add as many lines as necessary)
address:
  - line: University of Naples Federico II
  - line: Naples Italy

# Build settings
markdown: kramdown
permalink: pretty
